name: MLflow CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn

    - name: Run MLProject
      run: |
        # Berpindah ke folder MLProject dan menjalankan training
        cd MLProject
        mlflow run . --env-manager=local

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/model_output/

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image via MLflow
      run: |
        cd MLProject
        # Membungkus model menjadi API Docker dan memberikan tag nama
        mlflow models build-docker -m model_output -n ${{ secrets.DOCKER_USERNAME }}/football-model:latest

        # Mendorong (Push) image ke Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/football-model:latest